## Pandas is the popular library offen used in data analysis


In [32]:
import pandas as pd
import numpy as np
data=np.arange(1,21).reshape(5,4)
print("data : \n")
print(data)


data : 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [33]:
print("DataFrame") 
a=pd.DataFrame(data,index=['a','b','c','d','e'],columns=['x','y','z','w']) # ceating a datafrrame 
print(a)


DataFrame
    x   y   z   w
a   1   2   3   4
b   5   6   7   8
c   9  10  11  12
d  13  14  15  16
e  17  18  19  20


In [34]:
print("Coverting DataFrame into a csv file : ")
b=a.to_csv ('csv_dataframe') # creates a file 
print("csv file created")


Coverting DataFrame into a csv file : 
csv file created


In [37]:
print("Accessing the elements using .loc  : ")
print(a.loc['a']) # .loc uses row names
print("type :",type(a.loc['a']))


Accessing the elements using .loc  : 
x    1
y    2
z    3
w    4
Name: a, dtype: int32
type : <class 'pandas.core.series.Series'>


In [39]:
print("Acessing the elements using .iloc : ")
print(a.iloc[0:2,0:2]) # .iloc usies only indexing 
print(type(a.iloc[0:2,0:2]))

Acessing the elements using .iloc : 
   x  y
a  1  2
b  5  6
<class 'pandas.core.frame.DataFrame'>


In [30]:
print(a.loc[['a','b']]) # for multiple row we use list 
print("Data type :")
print(type(a.loc[['a','b']]))


   x  y  z  w
a  1  2  3  4
b  5  6  7  8
Data type :
<class 'pandas.core.frame.DataFrame'>


In [43]:
# Converting DaataFrame to array 
array=a.iloc[:,:].values   # .values --> converts data into array
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [52]:
print("null values : ")
print(a.isnull()) # checking for the null values 
print("No.of times each value repeated in the row :")
print(a['x'].value_counts()) # counts the each element 
print("UNique values in a row :")
print(a['x'].unique())

null values : 
       x      y      z      w
a  False  False  False  False
b  False  False  False  False
c  False  False  False  False
d  False  False  False  False
e  False  False  False  False
No.of times each value repeated in the row :
1     1
5     1
9     1
13    1
17    1
Name: x, dtype: int64
UNique values in a row :
[ 1  5  9 13 17]


In [58]:
# reading a csv file 
pd.read_csv('csv_dataframe')

Unnamed: 0   x   y   z   w
0          a   1   2   3   4
1          b   5   6   7   8
2          c   9  10  11  12
3          d  13  14  15  16
4          e  17  18  19  20

In [59]:
#  gives the info of our dataframe
print(a.info())

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, a to e
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x       5 non-null      int32
 1   y       5 non-null      int32
 2   z       5 non-null      int32
 3   w       5 non-null      int32
dtypes: int32(4)
memory usage: 292.0+ bytes
None


In [61]:
# gives mean , std  , min , max and someother  values of the elements of the column
# "describe() " function considers only int's and  floting values  
print(a.describe())

               x          y          z          w
count   5.000000   5.000000   5.000000   5.000000
mean    9.000000  10.000000  11.000000  12.000000
std     6.324555   6.324555   6.324555   6.324555
min     1.000000   2.000000   3.000000   4.000000
25%     5.000000   6.000000   7.000000   8.000000
50%     9.000000  10.000000  11.000000  12.000000
75%    13.000000  14.000000  15.000000  16.000000
max    17.000000  18.000000  19.000000  20.000000


In [74]:
print(a)
q=a['x']>5
print()
print(q)

r=a[a['y']>15]
print()
print(r)

    x   y   z   w
a   1   2   3   4
b   5   6   7   8
c   9  10  11  12
d  13  14  15  16
e  17  18  19  20

a    False
b    False
c     True
d     True
e     True
Name: x, dtype: bool

    x   y   z   w
e  17  18  19  20


In [1]:
import pandas as pd
import numpy as np
from io import StringIO ,BytesIO
#csv
data=('col1,col2,col3\n'
     'x,y,z\n'
     'a,b,c\n'
     '1,2,3')
print(data)


df=pd.read_csv(StringIO(data))
print(df)

#usecols --> to get specific col 

pd.read_csv(StringIO(data),usecols=['col1','col3'])

col1,col2,col3
x,y,z
a,b,c
1,2,3
  col1 col2 col3
0    x    y    z
1    a    b    c
2    1    2    3


C:\Users\garla\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


col1 col3
0    x    z
1    a    c
2    1    3

In [2]:
import pandas as pd
from io import StringIO

data = ('col1,col2,col3\n'
        'x,y,z\n'
        'a,b,c\n'
        '1,2,3')

# Read CSV
df = pd.read_csv(StringIO(data))

print(df)


  col1 col2 col3
0    x    y    z
1    a    b    c
2    1    2    3


In [3]:
a1=np.arange(1,21).reshape(5,4)
print(a1)
print()
adf1=pd.DataFrame(a1,index=['a','b','c','d','e'],columns=['A1','A2','A3','A4'])
print(adf1)
Arr=adf1.iloc[:,:].values
print("Arr : ",Arr)
type(Arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

   A1  A2  A3  A4
a   1   2   3   4
b   5   6   7   8
c   9  10  11  12
d  13  14  15  16
e  17  18  19  20
Arr :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


numpy.ndarray

In [4]:
d=('index,a,b,c\n'
  '4,apple,bat,5.7\n'
  '8,orange,cow,10')
D=pd.read_csv(StringIO(d),index_col=0) #index_col --> to select the col as the index 
print(D)

            a    b     c
index                   
4       apple  bat   5.7
8      orange  cow  10.0
